<?php
/**
 * TCPDF hook for codeigniter
 * @author cbrogan
 *
 */
require_once('/www/tcpdf/config/lang/eng.php');
require_once('/www/tcpdf/tcpdf.php');

class pdf_report extends TCPDF {
	private $report_author = '';
	private $report_name = '';
	private $report_app = '';
	
	public function set_report_author($report_author)
	{
		$this->report_author = $report_author;
	}
	
	public function set_report_name($report_name)
	{
		$this->report_name = $report_name;
	}
	
	public function set_report_app($report_app)
	{
		$this->report_app = $report_app;
	}
	
	public function check_page_break($h, $add_pg = TRUE)
	{
		return $this->checkPageBreak($h, '', $add_pg);
	}
	
	// Setup default header/footer information
	function setup_pdf()
	{		
		$this->SetDisplayMode('real');
		
		// set document information 
		$this->SetCreator(PDF_CREATOR);
		$this->SetAuthor($this->report_author);
		$this->SetTitle($this->report_name);
		$this->SetSubject($this->report_name);
	}	
	
	function Header() {
		$this->SetFont('helvetica', 'B', 10);
		$this->SetY(10, 0, TRUE);
		$this->Cell(0, 20, $this->report_app.' '.$this->report_name, 0, 0, 'R', 0);
	}
	
	// Page footer
    function Footer() {
        $this->SetY(-30);
        // Set font
        $this->SetFont('helvetica', 'I', 10);
        // Page number
        $this->Cell(50, 6, 'Generated by '.$this->report_author.' on '.date('n/j/Y'), 0, 0, 'L', 0);        
        $this->Cell(0, 6, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, 0, 'R'); 
    }
}