-- FIX FOR BUG #77: CONTRACT NAME LENGTH

-- CREATE TEMP TABLE
CREATE TABLE CTMCMA.CNTRCT_TMP LIKE CTMCMA.CNTRCT;

-- COPY RECORDS FROM CNTRCT TO CNTRCT_TMP
INSERT INTO CTMCMA.CNTRCT_TMP(CNTRCT_ID,APP,CSE_TP,STRT_DT,END_DT,VNDR_NO,CNTRCT_NM)
SELECT CNTRCT_ID,APP,CSE_TP,STRT_DT,END_DT,VNDR_NO,CNTRCT_NM
FROM CTMCMA.CNTRCT;

-- DROP CNTRCT
DROP TABLE CTMCMA.CNTRCT;

-- CREATE NEW CNTRCT TABLE WITH BIGGER CNTRCT_NM COLUMN
CREATE TABLE CTMCMA.CNTRCT
(
 CNTRCT_ID             INTEGER  NOT NULL ,
 APP                   CHAR(2)  ,
 CSE_TP                CHAR(2)  ,
 STRT_DT               DATE  ,
 END_DT                DATE  ,
 VNDR_NO               CHAR(5)  ,
 CNTRCT_NM             VARCHAR(80)  
);

LABEL ON TABLE CTMCMA.CNTRCT IS 'Contract';
LABEL ON COLUMN CTMCMA.CNTRCT.CNTRCT_ID IS 'Contract Identifier';
LABEL ON COLUMN CTMCMA.CNTRCT.CNTRCT_ID TEXT IS 'Contract Identifier:';
LABEL ON COLUMN CTMCMA.CNTRCT.APP IS 'Application';
LABEL ON COLUMN CTMCMA.CNTRCT.APP TEXT IS 'Application:';
LABEL ON COLUMN CTMCMA.CNTRCT.CSE_TP IS 'Case Type';
LABEL ON COLUMN CTMCMA.CNTRCT.CSE_TP TEXT IS 'Case Type:';
LABEL ON COLUMN CTMCMA.CNTRCT.STRT_DT IS 'Start Date';
LABEL ON COLUMN CTMCMA.CNTRCT.STRT_DT TEXT IS 'Start Date:';
LABEL ON COLUMN CTMCMA.CNTRCT.END_DT IS 'End Date';
LABEL ON COLUMN CTMCMA.CNTRCT.END_DT TEXT IS 'End Date:';
LABEL ON COLUMN CTMCMA.CNTRCT.VNDR_NO IS 'Vendor Number';
LABEL ON COLUMN CTMCMA.CNTRCT.VNDR_NO TEXT IS 'Vendor Number:';
LABEL ON COLUMN CTMCMA.CNTRCT.CNTRCT_NM IS 'Contract Name';
LABEL ON COLUMN CTMCMA.CNTRCT.CNTRCT_NM TEXT IS 'Contract Name:';

CREATE UNIQUE INDEX CTMCMA.XPKContract ON CTMCMA.CNTRCT
(
 CNTRCT_ID             ASC
);

ALTER TABLE CTMCMA.CNTRCT
 ADD PRIMARY KEY (CNTRCT_ID);

-- COPY RECORDS FROM CNTRCT_TMP TO CNTRCT
INSERT INTO CTMCMA.CNTRCT(CNTRCT_ID,APP,CSE_TP,STRT_DT,END_DT,VNDR_NO,CNTRCT_NM)
SELECT CNTRCT_ID,APP,CSE_TP,STRT_DT,END_DT,VNDR_NO,CNTRCT_NM
FROM CTMCMA.CNTRCT_TMP;

-- DROP TEMP TABLE
DROP TABLE CTMCMA.CNTRCT_TMP