-- FEATURE #108
DROP TABLE CTMCMA.NOTE;

CREATE TABLE CTMCMA.NOTE
(
 NOTE_ID               INTEGER  NOT NULL ,
 BODY                  VARCHAR(512)  ,
 FILE_EXT              CHAR(10)  ,
 LST_UPDT_TM           TIMESTAMP  ,
 CNTRCT_ID             INTEGER  NOT NULL ,
 FILE_NM               VARCHAR(40)  
);

LABEL ON TABLE CTMCMA.NOTE IS 'Note';
LABEL ON COLUMN CTMCMA.NOTE.NOTE_ID IS 'Note Identifier';
LABEL ON COLUMN CTMCMA.NOTE.NOTE_ID TEXT IS 'Note Identifier:';
LABEL ON COLUMN CTMCMA.NOTE.BODY IS 'Body';
LABEL ON COLUMN CTMCMA.NOTE.BODY TEXT IS 'Body:';
LABEL ON COLUMN CTMCMA.NOTE.FILE_EXT IS 'File Extension';
LABEL ON COLUMN CTMCMA.NOTE.FILE_EXT TEXT IS 'File Extension:';
LABEL ON COLUMN CTMCMA.NOTE.LST_UPDT_TM IS 'Last Update Time';
LABEL ON COLUMN CTMCMA.NOTE.LST_UPDT_TM TEXT IS 'Last Update Time:';
LABEL ON COLUMN CTMCMA.NOTE.CNTRCT_ID IS 'Contract Identifier';
LABEL ON COLUMN CTMCMA.NOTE.CNTRCT_ID TEXT IS 'Contract Identifier:';
LABEL ON COLUMN CTMCMA.NOTE.FILE_NM IS 'File Name';
LABEL ON COLUMN CTMCMA.NOTE.FILE_NM TEXT IS 'File Name:';

CREATE UNIQUE INDEX CTMCMA.XPKNote ON CTMCMA.NOTE
(
 NOTE_ID               ASC
);

ALTER TABLE CTMCMA.NOTE
 ADD PRIMARY KEY (NOTE_ID);
 
CREATE INDEX CTMCMA.XIF1Note ON CTMCMA.NOTE
(
 CNTRCT_ID             ASC
);