-- FEATURE #116 
CREATE TABLE CTMCMA.CNTRCT_PGM
(
 CNTRCT_ID             INTEGER  NOT NULL ,
 PGM_ID                INTEGER  NOT NULL 
);

LABEL ON TABLE CTMCMA.CNTRCT_PGM IS 'Contract Program';
LABEL ON COLUMN CTMCMA.CNTRCT_PGM.CNTRCT_ID IS 'Contract Identifier';
LABEL ON COLUMN CTMCMA.CNTRCT_PGM.CNTRCT_ID TEXT IS 'Contract Identifier:';
LABEL ON COLUMN CTMCMA.CNTRCT_PGM.PGM_ID IS 'Program Identifier';
LABEL ON COLUMN CTMCMA.CNTRCT_PGM.PGM_ID TEXT IS 'Program Identifier:';

CREATE UNIQUE INDEX CTMCMA.XPKContract_Program ON CTMCMA.CNTRCT_PGM
(
 CNTRCT_ID             ASC, 
 PGM_ID                ASC
);

ALTER TABLE CTMCMA.CNTRCT_PGM
 ADD PRIMARY KEY (CNTRCT_ID, PGM_ID);
 
CREATE INDEX CTMCMA.XIF1Contract_Program ON CTMCMA.CNTRCT_PGM
(
 CNTRCT_ID             ASC
);

CREATE INDEX CTMCMA.XIF2Contract_Program ON CTMCMA.CNTRCT_PGM
(
 PGM_ID                ASC
);