-- IMPLEMENTS FEATURE #35: ALLOW SINGLE FUNDING ELEMENT TO BE USED MULTIPLE TIMES ON CONTRACT

-- CREATE TEMPORARY TABLE TO HOLD RECORDS
CREATE TABLE CTMCMA.CNTRCT_ELEM_TMP LIKE CTMCMA.CNTRCT_ELEM;

-- COPY EXISTING RECORDS INTO TEMP TABLE
INSERT INTO CTMCMA.CNTRCT_ELEM_TMP (CNTRCT_ID,ELEM_ID,STRT_DT,END_DT,PYMT_FREQ)
SELECT CNTRCT_ID,ELEM_ID,STRT_DT,END_DT,PYMT_FREQ
FROM CTMCMA.CNTRCT_ELEM;

-- DROP EXISTING TABLE
DROP TABLE CTMCMA.CNTRCT_ELEM;

-- CREATE NEW TABLES
CREATE TABLE CTMCMA.CNTRCT_ELEM
(
 CNTRCT_ID             INTEGER  NOT NULL ,
 ELEM_ID               INTEGER  NOT NULL ,
 PYMT_FREQ             CHAR(2)  
);

LABEL ON TABLE CTMCMA.CNTRCT_ELEM IS 'Contract Element';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM.CNTRCT_ID IS 'Contract Identifier';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM.CNTRCT_ID TEXT IS 'Contract Identifier:';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM.ELEM_ID IS 'Element Identifier';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM.ELEM_ID TEXT IS 'Element Identifier:';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM.PYMT_FREQ IS 'Payment Frequency';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM.PYMT_FREQ TEXT IS 'Payment Frequency:';

CREATE UNIQUE INDEX CTMCMA.XPKContract_Element ON CTMCMA.CNTRCT_ELEM
(
 CNTRCT_ID             ASC, 
 ELEM_ID               ASC
);

ALTER TABLE CTMCMA.CNTRCT_ELEM
 ADD PRIMARY KEY (CNTRCT_ID, ELEM_ID);
 
CREATE INDEX CTMCMA.XIF1Contract_Element ON CTMCMA.CNTRCT_ELEM
(
 CNTRCT_ID             ASC
);

CREATE INDEX CTMCMA.XIF2Contract_Element ON CTMCMA.CNTRCT_ELEM
(
 ELEM_ID               ASC
);

CREATE TABLE CTMCMA.CNTRCT_ELEM_DT
(
 CNTRCT_ID             INTEGER  NOT NULL ,
 ELEM_ID               INTEGER  NOT NULL ,
 STRT_DT               DATE  NOT NULL ,
 END_DT                DATE  
);

LABEL ON TABLE CTMCMA.CNTRCT_ELEM_DT IS 'Contract Element Date';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.CNTRCT_ID IS 'Contract Identifier';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.CNTRCT_ID TEXT IS 'Contract Identifier:';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.ELEM_ID IS 'Element Identifier';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.ELEM_ID TEXT IS 'Element Identifier:';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.STRT_DT IS 'Start Date';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.STRT_DT TEXT IS 'Start Date:';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.END_DT IS 'End Date';
LABEL ON COLUMN CTMCMA.CNTRCT_ELEM_DT.END_DT TEXT IS 'End Date:';

CREATE UNIQUE INDEX CTMCMA.XPKContract_Element_Date ON CTMCMA.CNTRCT_ELEM_DT
(
 CNTRCT_ID             ASC, 
 ELEM_ID               ASC, 
 STRT_DT               ASC
);

ALTER TABLE CTMCMA.CNTRCT_ELEM_DT
 ADD PRIMARY KEY (CNTRCT_ID, ELEM_ID, STRT_DT);
 
CREATE INDEX CTMCMA.XIF1Contract_Element_Date ON CTMCMA.CNTRCT_ELEM_DT
(
 CNTRCT_ID             ASC
);

CREATE INDEX CTMCMA.XIF2Contract_Element_Date ON CTMCMA.CNTRCT_ELEM_DT
(
 ELEM_ID               ASC
);

-- ADD RECORDS BACK TO NEW TABLES
INSERT INTO CTMCMA.CNTRCT_ELEM (CNTRCT_ID,ELEM_ID,PYMT_FREQ)
SELECT CNTRCT_ID,ELEM_ID,PYMT_FREQ
FROM CTMCMA.CNTRCT_ELEM_TMP;

INSERT INTO CTMCMA.CNTRCT_ELEM_DT (CNTRCT_ID, ELEM_ID, STRT_DT, END_DT)
SELECT CNTRCT_ID, ELEM_ID, STRT_DT, END_DT
FROM CTMCMA.CNTRCT_ELEM_TMP;

-- DROP TMP TABLE
DROP TABLE CTMCMA.CNTRCT_ELEM_TMP;